# This compose file is for demonstration only, do not use in prod.
services:
  logto:
    depends_on:
    postgres:
      condition: service_healthy
    image: svhd/logto:1.21.0
    entrypoint: [ "sh", "-c", "npm run cli db seed -- --swe && npm start" ]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      TRUST_PROXY_HEADER: 1
      DB_URL: postgres://postgres:postgr3s@postgres:5432/logto
    volumes:
      - logto-connectors:/etc/logto/packages/core/connectors
  postgres:
    image: bitnami/postgresql:latest
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  logto-connectors:
